## Build
FROM golang:latest AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /notify-address

## Deploy
FROM scratch

WORKDIR /

COPY --from=build /notify-address /notify-address

ENTRYPOINT ["/notify-address"]